services:
  backend:
    build: ./backend
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    env_file:
      - .env
    #environment:
      # DATABASE_URL: ${DATABASE_URL}
      # STORAGE_URL: ${STORAGE_URL}
      # SUPABASE_URL: ${SUPABASE_URL}
      # SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      # EMBEDDING_MODEL: clap
      # EMBEDDING_DIM: "512"
      # HF_TOKEN: ${HF_TOKEN}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - .env
    environment:
      # - NEXT_PUBLIC_API_URL=http://localhost:8000/api
      # - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      # - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      # - PREVIEWS_BUCKET=${PREVIEWS_BUCKET}
      # - PRESETS_BUCKET=${PRESETS_BUCKET}
      - WATCHPACK_POLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- -H 0.0.0.0 -p 3000