services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
    environment:
      DATABASE_URL: ${DATABASE_URL}
      STORAGE_URL: ${STORAGE_URL}
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      EMBEDDING_MODEL: clap
      EMBEDDING_DIM: "512"
      HF_TOKEN: ${HF_TOKEN}
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:8000/api

      NEXT_PUBLIC_SUPABASE_URL: ${SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${SUPABASE_PUBLISHABLE_KEY}

      NEXT_PUBLIC_PREVIEWS_BUCKET: ${PREVIEWS_BUCKET}
      NEXT_PUBLIC_PRESETS_BUCKET: ${PRESETS_BUCKET}

      WATCHPACK_POLLING: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev